/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import rmi.common.EShopRemote;
import rmi.common.KundeRemote;
import rmi.common.MitarbeiterRemote;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;

/**
 *
 * @author Gruppe A4(Patrick, Oleksandra, Walter)
 */
public class login extends javax.swing.JFrame {

    private EShopRemote eshopartikel;
    private Vector kundenListe;
    private Vector mitarbeiterListe;
    /**
     * Creates new form login
     * setLocationRelativeTo(null); setzt das JFrame in der Mitte des Bildschirms
     */
    public login() throws IOException, RemoteException, NotBoundException {
        initComponents();
        setLocationRelativeTo(null);
        //eshopartikel = new EShopRemote("Datenbank");
        Registry registry = LocateRegistry.getRegistry();
        eshopartikel = (EShopRemote) registry.lookup("eshop");
        kundenListe = eshopartikel.gibKundenListe();
        mitarbeiterListe = eshopartikel.gibMitarbeiterListe();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLogin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelLoginWelcome = new javax.swing.JLabel();
        jRadioButtonLoginMit = new javax.swing.JRadioButton();
        jRadioButtonLoginKunde = new javax.swing.JRadioButton();
        jLabelLognName = new javax.swing.JLabel();
        jLabelLoginPassword = new javax.swing.JLabel();
        jTextFieldLoginname = new javax.swing.JTextField();
        jTextFieldLoginPassword = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jButtonReg = new javax.swing.JButton();
        jLabelLoginError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelLoginWelcome.setText("Willkommen bei unseren E-Shop. Bitte einloggen!");

        jRadioButtonLoginMit.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupLogin.add(jRadioButtonLoginMit);
        jRadioButtonLoginMit.setText("Mitarbeiter");
        jRadioButtonLoginMit.setSelected(true);

        jRadioButtonLoginKunde.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupLogin.add(jRadioButtonLoginKunde);
        jRadioButtonLoginKunde.setText("Kunde");

        jLabelLognName.setText("Login:");

        jLabelLoginPassword.setText("Password:");

        jTextFieldLoginname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginnameActionPerformed(evt);
            }
        });

        jTextFieldLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginPasswordActionPerformed(evt);
            }
        });

        jButtonLogin.setBackground(new java.awt.Color(0, 204, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonReg.setBackground(new java.awt.Color(0, 204, 255));
        jButtonReg.setText("Registrieren");
        jButtonReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegActionPerformed(evt);
            }
        });

        jLabelLoginError.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLoginError.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabelLoginWelcome)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLoginPassword)
                    .addComponent(jLabelLognName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLoginError, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jRadioButtonLoginMit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonLoginKunde))
                        .addComponent(jTextFieldLoginname, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addComponent(jButtonReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabelLoginWelcome)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonLoginMit)
                    .addComponent(jRadioButtonLoginKunde))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLognName)
                    .addComponent(jTextFieldLoginname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoginPassword)
                    .addComponent(jTextFieldLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLoginError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLoginnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginnameActionPerformed

    private void jTextFieldLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginPasswordActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        KundeRemote k = null;
        MitarbeiterRemote m = null;
        try {
            kundenListe = eshopartikel.gibKundenListe();
        } catch (IOException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(jRadioButtonLoginKunde.isSelected()== true){
            try {
                kundenListe = eshopartikel.gibKundenListe();
                Vector<KundeRemote> suchErgebnis = eshopartikel.sucheNachKunde(jTextFieldLoginname.getText());
                for (KundeRemote kunde: suchErgebnis){
                    String pw1 = jTextFieldLoginPassword.getText();
                    String pw2 = kunde.getPasswort();
                    
                    if(jTextFieldLoginPassword.getText().equalsIgnoreCase(pw2)){
                        try {
                            k = kunde;
                            this.setVisible(false);
                            new KundeJF(k).setVisible(true);
                            } catch (IOException ex) {
                                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (NotBoundException ex) {
                            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                        }  
                    } else jLabelLoginError.setText("Passwort falsch!");    
                }   
            } catch (IOException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }  
        } 
        
        
        if(jRadioButtonLoginMit.isSelected() == true){
            try {
                mitarbeiterListe = eshopartikel.gibMitarbeiterListe();
                Vector<MitarbeiterRemote> suchErgebnis = eshopartikel.sucheNachMitarbeiter(jTextFieldLoginname.getText());
                for (MitarbeiterRemote mitarbeiter: suchErgebnis){
                    String pw1 = jTextFieldLoginPassword.getText();
                    String pw2 = mitarbeiter.getPasswort();
                    
                    if(jTextFieldLoginPassword.getText().equalsIgnoreCase(pw2)){
                        try {
                            m = mitarbeiter;
                            this.setVisible(false);
                            new MitarbeiterJF(m).setVisible(true);
                            } catch (IOException ex) {
                                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (NotBoundException ex) {
                            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                        }  
                    } else jLabelLoginError.setText("Passwort falsch!");    
                }   
                
            } catch (IOException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegActionPerformed
        try {
            new RegistrierenJF().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    try {
                        new login().setVisible(true);
                    } catch (RemoteException ex) {
                        Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (NotBoundException ex) {
                        Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupLogin;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonReg;
    private javax.swing.JLabel jLabelLoginError;
    private javax.swing.JLabel jLabelLoginPassword;
    private javax.swing.JLabel jLabelLoginWelcome;
    private javax.swing.JLabel jLabelLognName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonLoginKunde;
    private javax.swing.JRadioButton jRadioButtonLoginMit;
    private javax.swing.JTextField jTextFieldLoginPassword;
    private javax.swing.JTextField jTextFieldLoginname;
    // End of variables declaration//GEN-END:variables
}
