/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.knowm.xchart.QuickChart;
import org.knowm.xchart.SwingWrapper;
import rmi.common.ArtikelExistiertBereitsException;
import rmi.common.ArtikelRemote;
import rmi.common.EShopRemote;
import rmi.common.EventRemote;
import rmi.common.MitarbeiterRemote;



/**
 *
 * @author Gruppe A4(Patrick, Oleksandra, Walter)
 */
public class MitarbeiterJF extends javax.swing.JFrame {
    private EShopRemote eshopartikel;
    private Vector<ArtikelRemote> artikelliste;
    private Vector<EventRemote> eventliste;
    private static MitarbeiterRemote eingeloggt;
    static String s;
    static String artnrString= "";
    static int artnr = 0;
    static int bestand = 0;
    static String bez = "";
    static String bestandString = "";
    static String preis ="";
    static int j = 0; 
    static int k = 0;
    static int l = 0;
    DefaultTableModel model;
    Map<Integer, Integer> bestandMap;

    /**
     * Creates new form MitarbeiterJF
     * @throws java.io.IOException
     */
    public MitarbeiterJF(MitarbeiterRemote mitarbeiter) throws IOException, RemoteException, NotBoundException  {
        initComponents();
        setLocationRelativeTo(null);
        Registry registry = LocateRegistry.getRegistry();
        eshopartikel = (EShopRemote) registry.lookup("eshop");
        artikelliste = eshopartikel.gibArtikelListe();
        eventliste = eshopartikel.gibEventListe();
        model = new DefaultTableModel();
        jTableLV.setModel(model);
        model.addColumn("Artnr");
        model.addColumn("Bezeichnung");
        model.addColumn("Preis");
        model.addColumn("Bestand");
        
        bestandMap = eshopartikel.gibArtikelbestand();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneEvent = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelLVArtikel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldLVartnr = new javax.swing.JTextField();
        jLabelLVartnr = new javax.swing.JLabel();
        jTextFieldLVbez = new javax.swing.JTextField();
        jLabelLFbez = new javax.swing.JLabel();
        jButtonLVartanlegen = new javax.swing.JButton();
        jTextFieldLVPreis = new javax.swing.JTextField();
        jLabelLFPreis = new javax.swing.JLabel();
        jLabelLFartanlegenBestand = new javax.swing.JLabel();
        jLabelLFArtanExcep = new javax.swing.JLabel();
        jButtonLVneuanlegen = new javax.swing.JButton();
        jComboBoxLV = new javax.swing.JComboBox<>();
        jTextFieldLVMasse = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldLVartnrb = new javax.swing.JTextField();
        jLabelLVartnrb = new javax.swing.JLabel();
        jLabelLFbezb = new javax.swing.JLabel();
        jTextFieldLVbezb = new javax.swing.JTextField();
        jLabelLFPreisb = new javax.swing.JLabel();
        jTextFieldLVPreisb = new javax.swing.JTextField();
        jLabelLFartanlegenBestandb = new javax.swing.JLabel();
        jButtonLVBestand = new javax.swing.JButton();
        jLabelLVBestandError = new javax.swing.JLabel();
        jTextFieldLVBestandb = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldLFArtSuchen = new javax.swing.JTextField();
        jLabelSuchenError = new javax.swing.JLabel();
        jButtonLFSuchen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLV = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanelEvent = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListEvent = new javax.swing.JList<>();
        jButtonEventAkt = new javax.swing.JButton();
        jButtonEventGrafik = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLVArtikel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Artikel anlegen"));

        jLabelLVartnr.setText("Artikelnummer:");

        jLabelLFbez.setText("Bezeichnung:");

        jButtonLVartanlegen.setBackground(new java.awt.Color(0, 204, 204));
        jButtonLVartanlegen.setText("Artikel anlegen");
        jButtonLVartanlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLVartanlegenActionPerformed(evt);
            }
        });

        jLabelLFPreis.setText("Preis:");

        jLabelLFartanlegenBestand.setText("Massengut:");

        jButtonLVneuanlegen.setBackground(new java.awt.Color(0, 204, 204));
        jButtonLVneuanlegen.setText("Neuen Artikel anlegen");
        jButtonLVneuanlegen.setEnabled(false);
        jButtonLVneuanlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLVneuanlegenActionPerformed(evt);
            }
        });

        jComboBoxLV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stück", "Kilo", "Meter", " " }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabelLFArtanExcep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonLVneuanlegen, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(jButtonLVartanlegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLVartnr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelLFbez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabelLFartanlegenBestand)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelLFPreis)
                                .addGap(60, 60, 60)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLVbez, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jTextFieldLVartnr)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextFieldLVMasse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxLV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextFieldLVPreis, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLVartnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLVartnr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLVbez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLFbez))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLFartanlegenBestand)
                    .addComponent(jComboBoxLV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLVMasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLFPreis)
                    .addComponent(jTextFieldLVPreis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabelLFArtanExcep, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLVartanlegen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLVneuanlegen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Bestand ändern"));

        jLabelLVartnrb.setText("Artikelnummer:");

        jLabelLFbezb.setText("Bezeichnung:");

        jLabelLFPreisb.setText("Preis:");

        jLabelLFartanlegenBestandb.setText("Bestand:");

        jButtonLVBestand.setBackground(new java.awt.Color(0, 204, 204));
        jButtonLVBestand.setText("Bestand ändern");
        jButtonLVBestand.setActionCommand("");
        jButtonLVBestand.setEnabled(false);
        jButtonLVBestand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLVBestandActionPerformed(evt);
            }
        });

        jLabelLVBestandError.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButtonLVBestand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLVBestandError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLVartnrb, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jLabelLFbezb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLFPreisb)
                                    .addComponent(jLabelLFartanlegenBestandb))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldLVPreisb)
                            .addComponent(jTextFieldLVbezb)
                            .addComponent(jTextFieldLVartnrb, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jTextFieldLVBestandb))))
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLVartnrb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLVartnrb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLVbezb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLFbezb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLVPreisb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLFPreisb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLFartanlegenBestandb)
                    .addComponent(jTextFieldLVBestandb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLVBestandError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButtonLVBestand)
                .addGap(21, 21, 21))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Artikel suchen"));

        jTextFieldLFArtSuchen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldLFArtSuchenKeyReleased(evt);
            }
        });

        jLabelSuchenError.setText(" ");

        jButtonLFSuchen.setBackground(new java.awt.Color(0, 204, 204));
        jButtonLFSuchen.setText("Suchen");
        jButtonLFSuchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLFSuchenActionPerformed(evt);
            }
        });

        jTableLV.setAutoCreateRowSorter(true);
        jTableLV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Artnr", "Bezeichnung", "Preis", "Bestand"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLV);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextFieldLFArtSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLFSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139)
                .addComponent(jLabelSuchenError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLFArtSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLFSuchen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSuchenError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLVArtikelLayout = new javax.swing.GroupLayout(jPanelLVArtikel);
        jPanelLVArtikel.setLayout(jPanelLVArtikelLayout);
        jPanelLVArtikelLayout.setHorizontalGroup(
            jPanelLVArtikelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLVArtikelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLVArtikelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 341, Short.MAX_VALUE)
                    .addGroup(jPanelLVArtikelLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanelLVArtikelLayout.setVerticalGroup(
            jPanelLVArtikelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLVArtikelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLVArtikelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLVArtikelLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLVArtikel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelLVArtikel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPaneEvent.addTab("Lagerverwaltung", jPanel1);

        jPanelEvent.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setViewportView(jListEvent);

        jButtonEventAkt.setBackground(new java.awt.Color(0, 204, 204));
        jButtonEventAkt.setText("Aktualisieren");
        jButtonEventAkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEventAktActionPerformed(evt);
            }
        });

        jButtonEventGrafik.setBackground(new java.awt.Color(0, 204, 204));
        jButtonEventGrafik.setText("Grafik");
        jButtonEventGrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEventGrafikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEventLayout = new javax.swing.GroupLayout(jPanelEvent);
        jPanelEvent.setLayout(jPanelEventLayout);
        jPanelEventLayout.setHorizontalGroup(
            jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                    .addGroup(jPanelEventLayout.createSequentialGroup()
                        .addComponent(jButtonEventAkt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEventGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelEventLayout.setVerticalGroup(
            jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEventLayout.createSequentialGroup()
                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEventAkt)
                    .addComponent(jButtonEventGrafik))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPaneEvent.addTab("Event", jPanel7);

        jMenu1.setText("Menu");

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLogout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneEvent)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneEvent)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        this.setVisible(false);
        try {
            new login().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MitarbeiterJF.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(MitarbeiterJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jButtonEventAktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEventAktActionPerformed
        jListEvent.removeAll();
        DefaultListModel listModel = new DefaultListModel();
        for(int i = 0; i<eventliste.size(); i++){

            try {
                switch(eventliste.get(i).getTyp()){
                    case HINZUGEFUEGT:
                    {
                        listModel.addElement(eventliste.get(i).getPerson().getName() + " hat "+ eventliste.get(i).getArtikel().getBez() +
                            " am " + eventliste.get(i).getDate() + " hinzugefügt.");

                        break;
                    }

                    case EINGELAGERT:
                    {

                        listModel.addElement(eventliste.get(i).getPerson().getName() + " hat "+ eventliste.get(i).getArtikel().getBez() +
                            " am " + eventliste.get(i).getDate() + " eingelagert.");
                        break;
                    }

                    case AUSGELAGERT:
                    {

                        listModel.addElement(eventliste.get(i).getPerson().getName() + " hat "+ eventliste.get(i).getArtikel().getBez() +
                            " am " + eventliste.get(i).getDate() + " ausgelagert.");
                        break;
                    }
                    case KAUF:
                    {
                        listModel.addElement(eventliste.get(i).getPerson().getName() + " hat "+ eventliste.get(i).getArtikel().getBez() +
                            " am " + eventliste.get(i).getDate() + " " + eventliste.get(i).getAnzahl() + " mal gekauft.");
                        break;

                    }
                    case GELOESCHT:
                    {
                        listModel.addElement(eventliste.get(i).getPerson().getName() + " hat "+ eventliste.get(i).getArtikel().getBez() +
                            " am " + eventliste.get(i).getDate() + " gelöscht");

                        break;
                    }

                }   } catch (RemoteException ex) {
                    Logger.getLogger(MitarbeiterJF.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

            jListEvent.setModel(listModel);
    }//GEN-LAST:event_jButtonEventAktActionPerformed

    private void jTableLVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLVMouseClicked
        int posx = jTableLV.getSelectedRow();

        jTextFieldLVartnrb.setText("" + jTableLV.getValueAt(posx, 0));
        jTextFieldLVbezb.setText("" + jTableLV.getValueAt(posx, 1));
        jTextFieldLVPreisb.setText("" + jTableLV.getValueAt(posx, 2));
        jTextFieldLVBestandb.setText("" + jTableLV.getValueAt(posx, 3));

        jButtonLVBestand.setEnabled(true);
    }//GEN-LAST:event_jTableLVMouseClicked

    private void jButtonLFSuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLFSuchenActionPerformed
        // listLVsuchErg.clear();
        model = new DefaultTableModel();
        jTableLV.setModel(model);
        model.addColumn("Artnr");
        model.addColumn("Bezeichnung");
        model.addColumn("Preis");
        model.addColumn("Bestand");
        jTextFieldLVartnrb.setText("");
        jTextFieldLVbezb.setText("");
        jTextFieldLVPreisb.setText("");
        jTextFieldLVBestandb.setText("");

        if(jTextFieldLFArtSuchen.getText().equalsIgnoreCase("")){

            try {
                List<ArtikelRemote> suchErgebnis = eshopartikel.gibArtikelListe();

                for (ArtikelRemote artikel: suchErgebnis) {
                    //model.addRow(new Object[]{artikel.getNummer(), artikel.getBez(), artikel.getPreis(), 0});
                    model.addRow(new Object[]{artikel.getNummer(), artikel.getBez(), artikel.getPreis(), bestandMap.get(Integer.parseInt(artikel.getNummer()))});
                }

            } catch (IOException ex) {
                Logger.getLogger(MitarbeiterJF.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            artnrString = "";
            bez = "";
            preis = "";
            bestandString = "";
            try {
                //            s = "" + eshopartikel.sucheNachArtikeltitel(jTextFieldLFArtSuchen.getText());
                Vector<ArtikelRemote> suchErgebnis = eshopartikel.sucheNachArtikeltitel(jTextFieldLFArtSuchen.getText());
                for (ArtikelRemote artikel: suchErgebnis) {
                    // model.addRow(new Object[]{artikel.getNummer(), artikel.getBez(), artikel.getPreis(), 0});
                    model.addRow(new Object[]{artikel.getNummer(), artikel.getBez(), artikel.getPreis(), bestandMap.get(Integer.parseInt(artikel.getNummer()))});

                }
            } catch (IOException ex) {
                Logger.getLogger(MitarbeiterJF.class.getName()).log(Level.SEVERE, null, ex);
                jLabelSuchenError.setForeground(Color.RED);
                jLabelSuchenError.setText("Keine Artikel gefunden!");
            }

        }
    }//GEN-LAST:event_jButtonLFSuchenActionPerformed

    private void jTextFieldLFArtSuchenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLFArtSuchenKeyReleased

    }//GEN-LAST:event_jTextFieldLFArtSuchenKeyReleased

    private void jButtonLVBestandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLVBestandActionPerformed

        bestandMap.put(Integer.parseInt(jTextFieldLVartnrb.getText()), Integer.parseInt(jTextFieldLVBestandb.getText()));
        try {
            eshopartikel.speicherBestand(bestandMap);
        } catch (IOException ex) {
            Logger.getLogger(MitarbeiterJF.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButtonLVBestandActionPerformed

    private void jButtonLVneuanlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLVneuanlegenActionPerformed
        jButtonLVartanlegen.setEnabled(true);
        jTextFieldLVartnr.setEnabled(true);
        jTextFieldLVbez.setEnabled(true);
        jTextFieldLVPreis.setEnabled(true);
        jButtonLVneuanlegen.setEnabled(false);
        jTextFieldLVartnr.setText("");
        jTextFieldLVbez.setText("");
        jTextFieldLVPreis.setText("");
        jLabelLFArtanExcep.setText("");
        jTextFieldLVMasse.setText(""); 

    }//GEN-LAST:event_jButtonLVneuanlegenActionPerformed

    private void jButtonLVartanlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLVartanlegenActionPerformed

        String nr = jTextFieldLVartnr.getText();
        String bez = jTextFieldLVbez.getText() + " " + jTextFieldLVMasse.getText() + " " + jComboBoxLV.getSelectedItem().toString();
        String preis = jTextFieldLVPreis.getText();
        String bestand = "0";
        try {
            eshopartikel.artikelAnlegen(nr, bez, preis);
            eshopartikel.schreibeArtikel();
            jLabelLFArtanExcep.setForeground(Color.GREEN);
            jLabelLFArtanExcep.setText("Artikel wurde angelegt!");
            jButtonLVneuanlegen.setEnabled(true);
            jButtonLVartanlegen.setEnabled(false);
            jTextFieldLVartnr.setEnabled(false);
            jTextFieldLVbez.setEnabled(false);
            jTextFieldLVPreis.setEnabled(false);

        } catch (ArtikelExistiertBereitsException e) {
            // Hier Fehlerbehandlung...
            jLabelLFArtanExcep.setForeground(Color.RED);
            jLabelLFArtanExcep.setText(e.getMessage());

        } catch (RemoteException ex) {
            Logger.getLogger(MitarbeiterJF.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MitarbeiterJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLVartanlegenActionPerformed

    private void jButtonEventGrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEventGrafikActionPerformed
//        try {
//            bestandMap = eshopartikel.gibArtikelbestand();
//        } catch (RemoteException ex) {
//            Logger.getLogger(MitarbeiterJF.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        int posx = jListEvent.getSelectedIndex();
//        double y1 = bestandMap.get(posx) ;
//        double y2;
//        double y3;
//        double y4;
        
        double[] xData = new double[] { 0.0, 1.0, 2.0, 3.0, 4.0 };
        double[] yData = new double[] { 2.0, 1.0, 0.0, 3.0, 6.0 };
        
    // Create Chart
        org.knowm.xchart.XYChart chart = QuickChart.getChart("Bestände", "Zeit", "Bestand", "y(x)", xData, yData);
 
    // Show it
       new SwingWrapper(chart).displayChart();
    }//GEN-LAST:event_jButtonEventGrafikActionPerformed
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MitarbeiterJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MitarbeiterJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MitarbeiterJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MitarbeiterJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new MitarbeiterJF(eingeloggt).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MitarbeiterJF.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(MitarbeiterJF.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEventAkt;
    private javax.swing.JButton jButtonEventGrafik;
    private javax.swing.JButton jButtonLFSuchen;
    private javax.swing.JButton jButtonLVBestand;
    private javax.swing.JButton jButtonLVartanlegen;
    private javax.swing.JButton jButtonLVneuanlegen;
    private javax.swing.JComboBox<String> jComboBoxLV;
    private javax.swing.JLabel jLabelLFArtanExcep;
    private javax.swing.JLabel jLabelLFPreis;
    private javax.swing.JLabel jLabelLFPreisb;
    private javax.swing.JLabel jLabelLFartanlegenBestand;
    private javax.swing.JLabel jLabelLFartanlegenBestandb;
    private javax.swing.JLabel jLabelLFbez;
    private javax.swing.JLabel jLabelLFbezb;
    private javax.swing.JLabel jLabelLVBestandError;
    private javax.swing.JLabel jLabelLVartnr;
    private javax.swing.JLabel jLabelLVartnrb;
    private javax.swing.JLabel jLabelSuchenError;
    private javax.swing.JList<String> jListEvent;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelEvent;
    private javax.swing.JPanel jPanelLVArtikel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneEvent;
    private javax.swing.JTable jTableLV;
    private javax.swing.JTextField jTextFieldLFArtSuchen;
    private javax.swing.JTextField jTextFieldLVBestandb;
    private javax.swing.JTextField jTextFieldLVMasse;
    private javax.swing.JTextField jTextFieldLVPreis;
    private javax.swing.JTextField jTextFieldLVPreisb;
    private javax.swing.JTextField jTextFieldLVartnr;
    private javax.swing.JTextField jTextFieldLVartnrb;
    private javax.swing.JTextField jTextFieldLVbez;
    private javax.swing.JTextField jTextFieldLVbezb;
    // End of variables declaration//GEN-END:variables
}
