/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import rmi.common.KundeRemote;



/**
 *
 * @author Aleksandra Solovei
 */
public class Rechnung extends javax.swing.JFrame {

    static KundeRemote k;
    static String rechnungsnr;
    static DefaultTableModel model;
    Date datum;
    /**
     * Creates new form Rechnung
     */
    public Rechnung(String rechnungsnr, KundeRemote  k, DefaultTableModel model) throws RemoteException {
        initComponents();
        this.k = k;
        this.rechnungsnr = rechnungsnr;
        datum = new Date();
        
        jTableRechnung.setModel(model);
        
        jLabelKundenName.setText(k.getVorname() + " " + k.getName());
        jLabelKundenAdresse.setText("" + k.getAdresse().getStrasse());
        jLabelKundenPLZ.setText(k.getAdresse().getPlz());
        jLabelKundenWohnort.setText(k.getAdresse().getWohnort());
        jLabelNummer.setText(rechnungsnr);
        jLabelDatum.setText("" + datum);
    //    jLabelSumme.setText(summe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDatum = new javax.swing.JLabel();
        jLabelKundenName = new javax.swing.JLabel();
        jLabelKundenAdresse = new javax.swing.JLabel();
        jLabelKundenPLZ = new javax.swing.JLabel();
        jLabelKundenWohnort = new javax.swing.JLabel();
        JLabelRechnungsnummer = new javax.swing.JLabel();
        jLabelNummer = new javax.swing.JLabel();
        javax.swing.JLabel jLabelRechnung = new javax.swing.JLabel();
        jLabelAnrede = new javax.swing.JLabel();
        jLabelAnrede2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRechnung = new javax.swing.JTable();
        jLabelGruß = new javax.swing.JLabel();
        jLabelGruß2 = new javax.swing.JLabel();
        jLabelESHOPName = new javax.swing.JLabel();
        jLabelESHOPAdresse = new javax.swing.JLabel();
        jLabelESHOPPLZ = new javax.swing.JLabel();
        jLabelTelefonnr = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelBankverbindung = new javax.swing.JLabel();
        jLabelKontonr = new javax.swing.JLabel();
        jLabelBLZ = new javax.swing.JLabel();
        jLabelBankname = new javax.swing.JLabel();
        jLabelSumme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelDatum.setText("Datum");

        jLabelKundenName.setText("Name");

        jLabelKundenAdresse.setText("Adresse");

        jLabelKundenPLZ.setText("PLZ");

        jLabelKundenWohnort.setText("Wohnort");

        JLabelRechnungsnummer.setText("Rechnungsnummer");

        jLabelNummer.setText("Nummer");

        jLabelRechnung.setText("RECHNUNG");

        jLabelAnrede.setText("Sehr geehrter Kunde,");

        jLabelAnrede2.setText("Bitte Ueberweisen Sie den folgenden Rechnungsbeitrag innerhalb von 14 Tagen auf das unten angegebene Konto.");

        jTableRechnung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRechnung);

        jLabelGruß.setText("Mit freundlichen Gruessen,");

        jLabelGruß2.setText("EShop ");

        jLabelESHOPName.setText("Eshop");

        jLabelESHOPAdresse.setText("Berliner Straße 23");

        jLabelESHOPPLZ.setText("01254 Berlin");

        jLabelTelefonnr.setText("+49 4432/955423");

        jLabelEmail.setText("eshop@gmx.de");

        jLabelBankverbindung.setText("Bankverbindung");

        jLabelKontonr.setText("123456789");

        jLabelBLZ.setText("12312312");

        jLabelBankname.setText("Deutsche Bank");

        jLabelSumme.setText("Summe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelESHOPName)
                            .addComponent(jLabelESHOPAdresse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTelefonnr, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelESHOPPLZ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBLZ)
                    .addComponent(jLabelBankname)
                    .addComponent(jLabelBankverbindung)
                    .addComponent(jLabelKontonr))
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKundenWohnort)
                    .addComponent(jLabelKundenAdresse)
                    .addComponent(jLabelKundenPLZ)
                    .addComponent(jLabelKundenName))
                .addGap(652, 652, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAnrede2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JLabelRechnungsnummer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDatum)
                        .addGap(135, 135, 135))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSumme)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelGruß2)
                                .addComponent(jLabelGruß)
                                .addComponent(jLabelNummer)
                                .addComponent(jLabelRechnung)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelAnrede)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelKundenName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKundenAdresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelKundenPLZ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKundenWohnort)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelRechnungsnummer)
                    .addComponent(jLabelDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNummer)
                .addGap(31, 31, 31)
                .addComponent(jLabelRechnung)
                .addGap(18, 18, 18)
                .addComponent(jLabelAnrede)
                .addGap(18, 18, 18)
                .addComponent(jLabelAnrede2)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSumme)
                .addGap(21, 21, 21)
                .addComponent(jLabelGruß)
                .addGap(18, 18, 18)
                .addComponent(jLabelGruß2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBankverbindung)
                    .addComponent(jLabelTelefonnr)
                    .addComponent(jLabelESHOPName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKontonr)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelESHOPAdresse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBLZ)
                    .addComponent(jLabelESHOPPLZ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBankname)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rechnung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rechnung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rechnung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rechnung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Rechnung(rechnungsnr, k, model).setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(Rechnung.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelRechnungsnummer;
    private javax.swing.JLabel jLabelAnrede;
    private javax.swing.JLabel jLabelAnrede2;
    private javax.swing.JLabel jLabelBLZ;
    private javax.swing.JLabel jLabelBankname;
    private javax.swing.JLabel jLabelBankverbindung;
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JLabel jLabelESHOPAdresse;
    private javax.swing.JLabel jLabelESHOPName;
    private javax.swing.JLabel jLabelESHOPPLZ;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGruß;
    private javax.swing.JLabel jLabelGruß2;
    private javax.swing.JLabel jLabelKontonr;
    private javax.swing.JLabel jLabelKundenAdresse;
    private javax.swing.JLabel jLabelKundenName;
    private javax.swing.JLabel jLabelKundenPLZ;
    private javax.swing.JLabel jLabelKundenWohnort;
    private javax.swing.JLabel jLabelNummer;
    private javax.swing.JLabel jLabelSumme;
    private javax.swing.JLabel jLabelTelefonnr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRechnung;
    // End of variables declaration//GEN-END:variables
}
